# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
