# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import twitter_auth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_auth', '0003_auto_20170908_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=b'images/', validators=[twitter_auth.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=2200),
        ),
        # migrations.RunPython(
        #
        # ),
    ]
