# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_auth', '0005_post_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='insta_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='telegram_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
